export const COL_CONTRATISTAS = 'col_contratistas';
export const COL_TRABAJADORES = 'col_trabajadores';
export const REF_HISTORIAL_OCUPACIONAL = 'col_historial_trabajadores_biod';
export const REF_TRABAJADORES_CONTRATISTAS = 'col_trabajadores_contratistas';
export const REF_EMAIL_TEMPLATE = 'col_plantillas_correos';
export const REF_EVA_CALIDAD = 'col_eva_comerciales';
export const REF_EVA_CONTRACTUAL = 'col_eva_contractuales';
export const USUARIOS = 'col_usuarios';
export const APP_BIOD_URL = 'https://hsebiod.biodsa.com.co'
export const LOGO_BIOD = 'https://firebasestorage.googleapis.com/v0/b/internal-bucket-biod/o/logo.webp?alt=media&token=a2d23927-3333-4beb-879c-db955b680596'
