import { PlantillaProps } from '../../types/ImportarTypes';

const listas: any = JSON.parse(
  localStorage?.getItem('listasTrabajadores') ?? JSON.stringify({})
);

const filtrarLista = (lista: any, tipoCampo: string) => {
  const listadoFil = lista?.map((item: any) => {
    return {
      value: item?.[tipoCampo] ?? '',
      label: item?.[tipoCampo] ?? '',
    };
  }) ?? [{ value: '', label: '' }];
  return listadoFil;
};

export const columnasExcelAusentismo: PlantillaProps[] = [
  {
    prop: 'documento_identidad',
    nonmbreColumna: 'documento_identidad',
    mostrarDato: true,
    obligatorio: true,
    readOnly: false,
    typeWord: 'number',
  },
  {
    prop: 'nombre_completo',
    nonmbreColumna: 'nombre_completo',
    mostrarDato: true,
    obligatorio: true,
    readOnly: false,
    typeWord: 'string',
  },
  {
    prop: 'fecha_nacimiento',
    nonmbreColumna: 'fecha_nacimiento',
    mostrarDato: true,
    obligatorio: false,
    readOnly: false,
    typeWord: 'string',
  },
  {
    prop: 'genero',
    nonmbreColumna: 'genero',
    mostrarDato: true,
    obligatorio: false,
    readOnly: false,
    typeWord: 'string',
  },
  {
    prop: 'estado_civil',
    nonmbreColumna: 'estado_civil',
    mostrarDato: true,
    tipoControl: 'select',
    lista: filtrarLista(listas?.estadoCivil ?? [], 'value') ?? [],
    obligatorio: true,
    readOnly: false,
    typeWord: 'string',
  },
  {
    prop: 'numero_ hijos',
    nonmbreColumna: 'numero_ hijos',
    mostrarDato: true,
    obligatorio: false,
    readOnly: false,
    typeWord: 'string',
  },
  {
    prop: 'nivel_educativo',
    nonmbreColumna: 'nivel_educativo',
    mostrarDato: true,
    tipoControl: 'select',
    lista: filtrarLista(listas?.nivelEducativo ?? [], 'value') ?? [],
    obligatorio: false,
    readOnly: false,
    typeWord: 'string',
  },
  {
    prop: 'profesion',
    nonmbreColumna: 'profesion',
    mostrarDato: true,
    tipoControl: 'select',
    lista: filtrarLista(listas?.profesiones ?? [], 'value') ?? [],
    obligatorio: false,
    readOnly: false,
    typeWord: 'string',
  },

  {
    prop: 'fecha_ingreso_empresa',
    nonmbreColumna: 'fecha_ingreso_empresa',
    mostrarDato: true,
    obligatorio: false,
    readOnly: false,
    typeWord: 'string',
  },

  {
    prop: 'fecha_retiro_empresa',
    nonmbreColumna: 'fecha_retiro_empresa',
    mostrarDato: true,
    obligatorio: false,
    readOnly: false,
    typeWord: 'string',
  },

  {
    prop: 'fecha_ingreso_cargo',
    nonmbreColumna: 'fecha_ingreso_cargo',
    mostrarDato: true,
    obligatorio: false,
    readOnly: false,
    typeWord: 'string',
  },
  {
    prop: 'fecha_retiro_cargo',
    nonmbreColumna: 'fecha_retiro_cargo',
    mostrarDato: true,
    obligatorio: false,
    readOnly: false,
    typeWord: 'string',
  },

  {
    prop: 'cargo',
    nonmbreColumna: 'cargo',
    mostrarDato: true,
    tipoControl: 'select',
    lista: filtrarLista(listas?.cargos ?? [], 'value') ?? [],
    obligatorio: false,
    readOnly: false,
    typeWord: 'string',
  },
  {
    prop: 'gerencia',
    nonmbreColumna: 'gerencia',
    mostrarDato: true,
    tipoControl: 'select',
    lista: filtrarLista(listas?.gerencias ?? [], 'value') ?? [],
    obligatorio: false,
    readOnly: false,
    typeWord: 'string',
  },
  {
    prop: 'proceso',
    nonmbreColumna: 'proceso',
    mostrarDato: true,
    tipoControl: 'select',
    lista: filtrarLista(listas?.procesos ?? [], 'value') ?? [],
    obligatorio: false,
    readOnly: false,
    typeWord: 'string',
  },
  {
    prop: 'turno',
    nonmbreColumna: 'turno',
    mostrarDato: true,
    tipoControl: 'select',
    lista: filtrarLista(listas?.turnos ?? [], 'value') ?? [],
    obligatorio: false,
    readOnly: false,
    typeWord: 'string',
  },
  {
    prop: 'jefe_inmediato',
    nonmbreColumna: 'jefe_inmediato',
    mostrarDato: true,
    obligatorio: false,
    readOnly: false,
    typeWord: 'string',
  },
  {
    prop: 'correo_electronico',
    nonmbreColumna: 'correo_electronico',
    mostrarDato: true,
    obligatorio: false,
    readOnly: false,
    typeWord: 'string',
  },
  {
    prop: 'tipo_contrato',
    nonmbreColumna: 'tipo_contrato',
    mostrarDato: true,
    tipoControl: 'select',
    lista: filtrarLista(listas?.contratos ?? [], 'value') ?? [],
    obligatorio: false,
    readOnly: false,
    typeWord: 'string',
  },
  {
    prop: 'nombre_contacto',
    nonmbreColumna: 'nombre_contacto',
    mostrarDato: true,
    obligatorio: false,
    readOnly: false,
    typeWord: 'string',
  },
  {
    prop: 'grupo_sanguineo',
    nonmbreColumna: 'grupo_sanguineo',
    mostrarDato: true,
    obligatorio: false,
    readOnly: false,
    typeWord: 'string',
  },
  {
    prop: 'RH',
    nonmbreColumna: 'RH',
    mostrarDato: true,
    tipoControl: 'select',
    lista: listas?.contratos ?? [],
    obligatorio: false,
    readOnly: false,
    typeWord: 'string',
  },
];

export const encabezadosPlantillas = {
  cedula: 'documento_identidad',
  nombre: 'nombre_completo',
  fechaNacimiento: 'fecha_nacimiento',
  genero: 'genero',
  estadoCivil: 'estado_civil',
  numHijos: 'numero_hijos',
  nivelEducativo: 'nivel_educativo',
  profesion: 'profesion',
  fechaIngresoEmp: 'fecha_ingreso_empresa',
  fechaRetiroEmp: 'fecha_retiro_empresa',
  fechaIngresoCargo: 'fecha_ingreso_cargo',
  fechaRetiroCargo: 'fecha_retiro_cargo',
  cargo: 'cargo',
  gerencia: 'gerencia',
  proceso: 'proceso',
  turno: 'turno',
  jefeInmediato: 'jefe_inmediato',
  correo: 'correo_electronico',
  tipoContrato: 'tipo_contrato',
  nombreContacto: 'nombre_contacto',
  numContacto: 'numero_contacto',
  grupoSanguineo: 'grupo_sanguineo',
  rh: 'RH',
};
